const PRIMARY_NORMAL = '#0b9444';
const PRIMARY_BACKGROUND = '#e1e2e1';
const SECONDARY_COLOR = '#f5f5f6';
const PRIMARY_LIGHT = '#52c671';
const PRIMARY_DARK = '#006519';
const PRIMARY_NORMAL_FONT_COLOR = '#000';
const PRIMARY_LIGHT_FONT_COLOR = '#000';
const PRIMARY_DARK_FONT_COLOR = '#fff';
const SECONDARY_NORMAL = '#3a3a3c';
const SECONDARY_LIGHT = '#646466';
const SECONDARY_DARK = '#141416';
const SECONDARY_FONT_COLOR = '#fff';

export {SECONDARY_DARK, PRIMARY_DARK_FONT_COLOR, SECONDARY_NORMAL, PRIMARY_LIGHT_FONT_COLOR, PRIMARY_BACKGROUND, PRIMARY_NORMAL_FONT_COLOR, PRIMARY_LIGHT, SECONDARY_FONT_COLOR, PRIMARY_NORMAL, SECONDARY_LIGHT, PRIMARY_DARK, SECONDARY_COLOR}
